(add-hook 'c-mode-hook 'my-c-mode)
(add-hook 'c++-mode-hook 'my-c-mode)
(defun my-c-mode()
  (interactive)
  (define-key c-mode-map (kbd "<return>") 'newline-and-indent)
  (define-key c++-mode-map (kbd "<return>") 'newline-and-indent)
  (define-key c-mode-map (kbd "C-m") 'newline-and-indent)
  (define-key c++-mode-map (kbd "C-m") 'newline-and-indent)
  ;; (define-key c-mode-map (kbd "C-?") 'c-hungry-delete-backwards)
  ;; (define-key c++-mode-map (kbd "C-?") 'c-hungry-delete-backwards)
  ;; (define-key c-mode-map (kbd "<backspace>") 'c-hungry-delete-backwards)
  ;; (define-key c++-mode-map (kbd "<backspace>") 'c-hungry-delete-backwards)
  (define-key c-mode-map (kbd "M-j") 'windmove-down)
  (define-key c++-mode-map (kbd "M-j") 'windmove-down)
  (setq indent-tabs-mode nil)
  (c-set-style "K&R")
  (c-toggle-hungry-state t)
  (setq c-basic-offset 4)
  (imenu-add-menubar-index)
  (which-function-mode t)
  )
(require 'xcscope)
