(add-hook 'c-mode-hook 'my-c-mode)
(add-hook 'c++-mode-hook 'my-c-mode)
(defun my-c-mode()
  (interactive)
  (define-key c-mode-map [return] 'newline-and-indent)
  (define-key c++-mode-map [return] 'newline-and-indent)
  (setq indent-tabs-mode nil)
  (c-set-style "K&R")
  (c-toggle-hungry-state)
  (setq c-basic-offset 4)
  (imenu-add-menubar-index)
  (which-function-mode t)
  )
(require 'xcscope)
