# Init Zsh
[[ -o interactive ]] || return

ZSH="${HOME}/.config/zsh"
source "$ZSH/loader.zsh"
return

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git archlinux)

# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall

# End of lines added by compinstall
